# -*- coding: utf-8 -*-
"""Limpeza_tratamento_churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8uHGBudiDLvb4eZI-EdvzJnloxgp1ej

# Análise de Churn de Clientes de Telecomunicações

Este notebook explora um dataset de churn de clientes para identificar padrões e fatores que levam à evasão de clientes em uma empresa de telecomunicações. - Curso "Pandas: limpeza e tratamento de dados" da Alura

Bibliotecas usadas: pandas,
json,
numpy,
seaborn,
matplotlib.pyplot

link do arquivo json no drive: https://drive.google.com/file/d/1nD4_h6dMyooFr-noMpJjENvXwbVJpgXu/view?usp=sharing
"""

import pandas as pd

dados_churn = pd.read_json("dataset-telecon.json")

dados_churn['conta'][0]

pd.json_normalize(dados_churn['conta']).head()

pd.jason_normalize(dados_churn['telefone']).head()

"""# Transformando dados em uma tabela

"""

import json

with open ("dataset-telecon.json") as f:
  json_bruto = json.load(f)

json_bruto

dados_normalizados = pd.json_normalize(json_bruto)
dados_normalizados.head()

dados_normalizados.info()

"""# Modificando o tipo de coluna"""

dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].head()

dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '][
    ['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total' ]
]

idx = dados_normalizados[dados_normalizados['conta.cobranca.Total'] == ' '].index

dados_normalizados.loc[idx, 'conta.cobranca.Total'] = dados_normalizados.loc[idx, 'conta.cobranca.mensal'] * 24

dados_normalizados.loc[idx, 'cliente.tempo_servico'] = 24

dados_normalizados.loc[idx][
    ['cliente.tempo_servico', 'conta.contrato', 'conta.cobranca.mensal', 'conta.cobranca.Total' ]
]

dados_normalizados['conta.cobranca.Total'] = dados_normalizados['conta.cobranca.Total'].astype(float)

dados_normalizados.info()

"""# Identificando e tratando strings vazias"""

for col in dados_normalizados.columns:
  print(f"Coluna: {col}")
  print(dados_normalizados[col].unique())
  print("-"*50)

dados_normalizados.query("Churn == ' ' ")

dados_normalizados[dados_normalizados['Churn'] != ' ']

dados_sem_vazio = dados_normalizados[dados_normalizados['Churn'] != ' '].copy()

dados_sem_vazio.info()

dados_sem_vazio.reset_index(drop= True, inplace= True)

dados_sem_vazio

"""# Trabalhando com dados duplicados e nulos

Identificando e tratando dados duplicados
"""

dados_sem_vazio.duplicated()

dados_sem_vazio.duplicated().sum()

filtro_duplicados = dados_sem_vazio.duplicated()
filtro_duplicados

dados_sem_vazio [filtro_duplicados]

dados_sem_vazio.drop_duplicates(inplace= True)

dados_sem_vazio.duplicated().sum()

"""# Identificando e substituindo dados nulos"""

dados_sem_vazio.isna()

dados_sem_vazio.isna().sum()

dados_sem_vazio.isna().sum().sum()

dados_sem_vazio[dados_sem_vazio.isna().any(axis=1)]

dados_sem_vazio['cliente.tempo_servico'].isna()

filtro = dados_sem_vazio['cliente.tempo_servico'].isna()

dados_sem_vazio[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

import numpy as np

np.ceil(5957.90/90.45)

dados_sem_vazio['cliente.tempo_servico'].fillna(
    np.ceil(
        dados_sem_vazio['conta.cobranca.Total'] /dados_sem_vazio['conta.cobranca.mensal']
        ),
    inplace= True
    )

dados_sem_vazio[filtro][['cliente.tempo_servico', 'conta.cobranca.mensal', 'conta.cobranca.Total']]

dados_sem_vazio.isna().sum()

"""# Retirando os dados nulos"""

dados_sem_vazio['conta.contrato'].value_counts()

colunas_dropar = ['conta.contrato', 'conta.faturamente_eletronico', 'conta.metodo_pagamento']

dados_sem_vazio[colunas_dropar].isna().any(axis=1).sum()

df_sem_nulos = dados_sem_vazio.dropna(subset=colunas_dropar).copy()
df_sem_nulos.head()

df_sem_nulos.reset_index(drop=True, inplace=True )

df_sem_nulos.isna().sum()

"""# Substituindo valores para os outliers"""

df_sem_out = df_sem_nulos.copy()

Q1 = df_sem_out['cliente.tempo_servico'].quantile(0.25)
Q3 = df_sem_out['cliente.tempo_servico'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers_index = df_sem_out[(df_sem_out['cliente.tempo_servico'] < lower_bound) | (df_sem_out['cliente.tempo_servico'] > upper_bound)].index
df_sem_out.loc[outliers_index, 'cliente.tempo_servico']

df_sem_out.loc[outliers_index]['cliente.tempo_servico']

df_sem_out.loc[outliers_index, 'cliente.tempo_servico'] = np.ceil(
    df_sem_out.loc[outliers_index, 'conta.cobranca.Total'] /
    df_sem_out.loc[outliers_index, 'conta.cobranca.mensal']
    )

import seaborn as sns
sns.boxplot(x=df_sem_out['cliente.tempo_servico'])

df_sem_out.loc[outliers_index, ['cliente.tempo_servico' ,'conta.cobranca.mensal',
                           'conta.cobranca.Total']]

"""# Removendo outliers"""

df_sem_out.loc[outliers_index,['cliente.tempo_servico']]

Q1 = df_sem_out['cliente.tempo_servico'].quantile(0.25)
Q3 = df_sem_out['cliente.tempo_servico'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers_index = df_sem_out[(df_sem_out['cliente.tempo_servico'] < lower_bound) | (df_sem_out['cliente.tempo_servico'] > upper_bound)].index
df_sem_out.loc[outliers_index, 'cliente.tempo_servico']

df_sem_out.loc[outliers_index]

df_sem_out = df_sem_out.drop(outliers_index)
df_sem_out

sns.boxplot(x=df_sem_out['cliente.tempo_servico'])

df_sem_out.reset_index(drop=True, inplace=True)

df_sem_out

"""# TRABALHANDO COM VARIÁVEIS CATEGÓRICAS

Substituindo Valores
"""

df_sem_out.drop('id_cliente', axis=1)

df_sem_id = df_sem_out.drop('id_cliente', axis=1).copy()

df_sem_id

mapeamento = {
    'nao': 0,
    'sim': 1,
    'masculino': 0,
    'feminino': 1,
}

for col in df_sem_id.columns:
  print(f"Coluna: {col}")
  print(df_sem_id[col].unique())
  print("-"*50)

colunas = ['telefone.servico_telefone', 'Churn', 'cliente.parceiro','cliente.dependentes',
           'conta.faturamente_eletronico']

df_sem_id[colunas] = df_sem_id[colunas].replace(mapeamento)

for col in colunas:
  print(f"Coluna: {col}")
  print(df_sem_id[col].unique())
  print("-"*50)

"""# One Hot Encoder (dummy)"""

s = pd.Series(list('abca'))
s

pd.get_dummies(s)

df_sem_id.info()

pd.get_dummies(df_sem_id['conta.contrato'])

df_dummies = pd.get_dummies(df_sem_id).copy()
df_dummies.head()

df_dummies.columns

df_dummies.info()

